version: "3.7"

services:
  mysql:
    container_name: mysql
    image: mysql:8.4.2
    environment:
      MYSQL_ROOT_PASSWORD: kS9CP3Cg3JNug7gdSaZd
    ports:
      - 3306:3306
    volumes:
      - ./.data/mysql:/var/lib/mysql
    networks:
      - nptucsai

networks:
  nptucsai:
    driver: bridge


